config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  #resources :categories, only: [:index]
  root 'welcome#index'
  resources :courses, only: [:show, :index]
	devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations" }
  devise_for :admins, path: 'admin', skip: [:registrations]
	mount RailsAdmin::Engine => '/user_admin', as: 'rails_admin'
	mount Commontator::Engine => '/commontator'
  
  resources :blogs, path: "blog", only: [:show, :index]
  
	# get '/courses', to: redirect("http://courses.shetabyad.com/")
  
	get 'about-us', to: :about_us, controller: 'welcome'
	match '/contacts', path: 'contact-us', to: 'contacts#new', via: 'get'
	resources 'contacts', path: 'contact-us', only: [:new, :create]
	
  resources :tutorials, only: [:show, :index]
	
  
	#authenticate :user do 
		resources :lessons, only: [:show, :index] do 
			member do
				get 'like'
			end
		end
	#end
  
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  
  resources :tutorial_types, path: "", only: [:show]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :blogs
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/blog.rb
class Blog < ApplicationRecord
  
  extend FriendlyId
  friendly_id :title_url, use: :slugged
  
  mount_uploader :picture, ImageUploader
  
  belongs_to :admin
  
  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tutorial_types
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true
  attribute :tel,       :validate => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "پیام کاربر از شتابیاد",
      :to => "info@shetabyad.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/course.rb
class Course < ApplicationRecord
  extend FriendlyId
  friendly_id :title_url, use: :slugged
  
  mount_uploader :image, ImageUploader
  has_one :video
  
  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  validates :description, presence: true, length: { maximum: 100 }
  extend FriendlyId
  friendly_id :title_url, use: :slugged
  
	acts_as_votable
  mount_uploader :image, ImageUploader
	mount_uploader :thumbnail_image, ImageUploader
	mount_uploader :lesson_video, VideoUploader
  #belongs_to :tutorial
	has_one :video
  belongs_to :section
	#has_many :comments, dependent: :destroy

	

  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :lessons
  belongs_to :tutorial
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  ratyrate_rateable "rate"
  validates :description, presence: true, length: { maximum: 400 }
	mount_uploader :images, ImageUploader
  #has_many :lessons
  has_many :sections
  belongs_to :tutorial_type
  acts_as_commontable
  
  extend FriendlyId
  friendly_id :title_url, use: :slugged

  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/tutorial_type.rb
class TutorialType < ApplicationRecord
  
  extend FriendlyId
  friendly_id :title_url, use: :slugged

  has_many :tutorials
  belongs_to :category

  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ratyrate_rater
	acts_as_voter
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
	#has_many :comments, dependent: :destroy
	acts_as_commontator
end

app/models/video.rb
class Video < ApplicationRecord
	belongs_to :lesson
  belongs_to :course
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
	def display_likes(lesson)
		votes = lesson.votes_for.up.by_type(User)
		return list_likers(votes) if votes.size <= 3
		count_likers(votes)
	end
	
	def liked_lesson(lesson)
		if user_signed_in?
			return 'fa fa-heart' if current_user.voted_for? lesson
			'fa fa-heart-o'
		end
	end
	
	def last_models(number)
		if number <= Lesson.count
			Lesson.last(number)	
		end
	end
	
	private

	def all_lessons
		Lesson.last(3)
	end
	
	def list_likers(votes)
		emails = []
		unless votes.blank?
			votes.voters.each do |voter|
				emails.push(voter.email, class: 'some')
			end
			emails.to_sentence.html_safe + like_plural(votes)
	end
end

	def count_likers(votes)
		vote_count = votes.size
		vote_count.to_s + ' likes'
	end
	
	def like_plural(votes)
		return ' like this' if votes.count > 1
		' likes this'
	end
end
	

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/commontator/shared/_thread.html.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
%>

<% if thread.can_be_read_by?(user) %>
  <div id="thread_<%= thread.id %>_div" class="thread" style="display: none;">
    <% if @commontator_thread_show %>
      <%= render :partial => 'commontator/threads/show',
                 :locals => { :thread => thread,
                              :user => user,
                              :page => @commontator_page,
                              :per_page => @commontator_per_page } %>
    <% else %>
      <% subscription = thread.subscription_for(user) %>
      <%= link_to "#{t 'commontator.thread.actions.show'} (#{(subscription.unread_comments.count.to_s + '/') if subscription}#{thread.filtered_comments.count.to_s})",
                  commontator.thread_path(thread),
                  :remote => true %>
    <% end %>
  </div>
<% end %>

app/views/commontator/subscriptions/_link.html.erb
<% # Clients of this partial must supply the following variables:
   # thread
   # user
%>

<% is_subscribed = !!thread.subscription_for(user) %>
<% sub_string = is_subscribed ? "unsubscribe" : "subscribe" %>
<%= link_to t("commontator.subscription.actions.#{sub_string}"),
            commontator.polymorphic_path([sub_string, thread]),
            :confirm => (is_subscribed ? t('commontator.subscription.actions.confirm_unsubscribe') : \
                          nil),
            :method => :put,
            :id => "thread_#{thread.id.to_s}_#{sub_string}_link",
            :class => "thread_#{sub_string}_link",
            :remote => true %>

app/views/commontator/subscriptions/subscribe.js.erb
$("#thread_<%= @thread.id.to_s %>_subscription_span").html("<%= escape_javascript(
  render :partial => 'link',
         :locals => { :thread => @thread,
                      :user => @user }) %>");

<%= javascript_proc %>

app/views/shared/_footer.html.erb
<footer>
	<div class="container">
		<div class="row first">
			<div class="col-md-4 col-xs-12 col-sm-12 pull-right">
				<%#= image_tag 'logo.svg', size: "100x100", class: "logo-img" %>
				<%= link_to 'شتابیاد', root_path, class: "footer-brand" %>
				<!-- <p class="footer-brand">شتابیاد</p> -->
				<p>&copy; تمام حقوق مادی و معنوی این وبسایت متعلق به شتابیاد می باشد. ۱۳۹۶-۱۳۹۷</p>
				<div class="footer-socials">
					<a href="https://www.instagram.com/shetabyaad/"><i class="fa fa-instagram fa-lg"></i></a>
					<a href="https://github.com/shetabyad"><i class="fa fa-github fa-lg"></i></a>
					<a href="https://www.twitter.com/shetabyaad"><i class="fa fa-twitter fa-lg"></i></a>
					<%= link_to (image_tag 'aparat.png', size: "20x20"), "https://www.aparat.com/shetabyad" %>
				</div>
			</div>
			<div class="col-md-8 col-xs-8 col-sm-8 pull-right">
				<div class="col-md-3 col-xs-12 col-sm-12">
					<p class="title">دوره های شتابیاد</p>
					<p><a href="http://courses.shetabyad.com">وبسایت دوره های شتابیاد</a> پایگاهی برای خرید دوره های تخصصی و کامل آموزش های روبی آن ریلز و آی او اس ما می باشد.<p>
						<a class="btn btn-success" href="http://courses.shetabyad.com">ورود به دوره های شتابیاد</a>
				</div>
				<!-- <div class="col-md-3 col-xs-12 col-sm-12">
					<p class="title">انجمن شتابیاد</p>
					<p><a href="http://forum.shetabyad.com">انجمن شتابیاد</a> محلی برای بحث و تبادل نظر و طرح سوالات بین کاربران شتابیاد و همه علاقه مندان روبی آن ریلز می باشد. <p>
						<a class="btn btn-success" href="http://forum.shetabyad.com">ورود به انجمن شتابیاد</a>
				</div> -->
				<div class="col-md-3 col-xs-12 col-sm-12">
					<p class="title">بیاموزید</p>
					<p><%= link_to TutorialType.first.title, TutorialType.first if TutorialType.any? %></p>
					<p><%= link_to TutorialType.last.title, TutorialType.last if TutorialType.any? %></p>
				</div>
				<div class="col-md-3 col-xs-12 col-sm-12">
					<p class="title">درباره</p>
					<p><%= link_to 'وبلاگ', blogs_path %></p>
					<p><%= link_to 'درباره ما', about_us_path %></p>
	        <p><%= link_to 'تماس با ما', contacts_path %></p>
				</div>
			</div>
		</div>
	</div>
</footer>

app/views/shared/_nav_blog.html.erb
<nav class="navbar navbar-custom navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header pull-right">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag 'logo.svg', size:'40x40' %><%= link_to "شتابیاد <span style='font-size:18px;'><em>بتا</em></span>".html_safe, root_path, class: "navbar-brand img-responsive" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<% if user_signed_in? %>
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span><i class="fa fa-user-circle-o"></i>  <%= current_user.username %> </a>
						<ul class="dropdown-menu">
							<li><%= link_to "<i class='fa fa-user'></i> حساب کاربری".html_safe, edit_user_registration_path %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to "<i class='fa fa-sign-out'></i> خروج".html_safe, destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>
				</ul>
			<% end %>
        
      <ul class="nav navbar-nav navbar-left">
				<li><%= link_to 'درباره ما', about_us_path %></li>
        <li><%= link_to 'تماس با ما', contacts_path %></li>
				<li><%= link_to 'دوره ها', courses_path %></li>
				<li><%= link_to 'وبلاگ', blogs_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header pull-right">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "شتابیاد <span style='font-size:18px;'><em>بتا</em></span>".html_safe, root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		 <ul class="nav navbar-nav">
       <li>
				 <a href="#" class="dropdown-toggle" data-toggle="dropdown">دسته ها<b class="caret"></b></a>
				 <ul class="dropdown-menu multi-level">
						 <% Category.all.each do |category| %>
						 	<li class="dropdown-submenu">
	 						 <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= category.title %></a>
							 <%#= link_to tutorial_type.title, tutorial_type, class: "dropdown-toggle", data: {toggle: "dropdown"} %>
	 						 <ul class="dropdown-menu">
	 							 <% category.tutorial_types.each do |tutorial_type| %>
										<li><%= link_to tutorial_type.title, tutorial_type %></li>
								 <% end %>
	 						 </ul>
							 </li>
						 <% end %>
				 </ul>
			 </li>
		 </ul>
		 	 
			<% if user_signed_in? %>
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown pull-right">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span><i class="fa fa-user-circle-o"></i>  <%= current_user.username %> </a>
						<ul class="dropdown-menu pull-right">
							<li><%= link_to "<i class='fa fa-user'></i> حساب کاربری".html_safe, edit_user_registration_path %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to "<i class='fa fa-sign-out'></i> خروج".html_safe, destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>
				</ul>
			<% end %>
			
			<% unless user_signed_in? %>
				<ul class="nav navbar-nav navbar-right">
	        <li><%= link_to "ورود", new_user_session_path, class: "login-user" %></li>
				</ul>
			<% end %>
        
      <ul class="nav navbar-nav navbar-left">
				<li><%= link_to 'دوره ها', courses_path %><!-- <i class="fa fa-laptop"></i> --></li>
				<li><%= link_to 'درباره ما', about_us_path %><!-- <i class="fa fa-laptop"></i> --></li>
				<li><%= link_to 'وبلاگ', blogs_path %><!-- <i class="fa fa-rss"></i> --></li>
				<!-- <li class="blog-navbar"><%= link_to 'انجمن شتابیاد', "http://forum.shetabyad.com", target: "_blank" %> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_signup.html.erb
<div class="well" align="center">
		<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
			<%= devise_error_messages! %>
		
			<% unless resource_name == :admin %>
				<div class="form-group">
					<i class="fa fa-user  fauser"></i><%= f.text_field :username, autofocus: true, placeholder: "نام و نام خانوادگی" , required: true, class: "form-control" %>
				</div>
			<% end %>
		
			<div class="form-group">
				<i class="fa fa-envelope-o  faemail"></i><%= f.email_field :email, autofocus: true, placeholder: "ایمیل" , required: true, class: "form-control" %>
			</div>

			<div class="form-group">
				<i class="fa fa-lock  fapassword"></i><%= f.password_field :password, autocomplete: "off", placeholder: "رمز عبور", required: true, class: "form-control" %>
			</div>

			<div class="form-group">
				<i class="fa fa-lock  fapassword-confirm"></i><%= f.password_field :password_confirmation, placeholder: "تکرار رمز عبور", required: true, autocomplete: "off", class: "form-control" %>
			</div>

			<div class="actions form-group">
				<%= f.button "<i class='fa fa-user-plus'></i> ثبت نام".html_safe, class: "btn btn-block btn-success", data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> ساخت حساب کاربری" } %>
			</div>
		<% end %>
	<!-- </div> -->
	<!-- <div class="panel-footer"> -->
		<% unless resource_name == :admin %>
			<%#= render "devise/shared/links" %>
		<% end %>
	<!-- </div> -->
</div>