config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  #resources :categories, only: [:index]
  root 'welcome#index'
  resources :courses, only: [:show, :index]
	devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations" }
  devise_for :admins, path: 'admin', skip: [:registrations]
	mount RailsAdmin::Engine => '/user_admin', as: 'rails_admin'
	mount Commontator::Engine => '/commontator'
  
  resources :blogs, path: "blog", only: [:show, :index]
  
	# get '/courses', to: redirect("http://courses.shetabyad.com/")
  
	get 'about-us', to: :about_us, controller: 'welcome'
	match '/contacts', path: 'contact-us', to: 'contacts#new', via: 'get'
	resources 'contacts', path: 'contact-us', only: [:new, :create]
	
  resources :tutorials, only: [:show, :index]
	
  
	#authenticate :user do 
		resources :lessons, only: [:show, :index] do 
			member do
				get 'like'
			end
		end
	#end
  
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  
  resources :tutorial_types, path: "", only: [:show]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/blog.rb
class Blog < ApplicationRecord
  
  extend FriendlyId
  friendly_id :title_url, use: :slugged
  
  mount_uploader :picture, ImageUploader
  
  belongs_to :admin
  
  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tutorial_types
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true
  attribute :tel,       :validate => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "پیام کاربر از شتابیاد",
      :to => "info@shetabyad.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/course.rb
class Course < ApplicationRecord
  extend FriendlyId
  friendly_id :title_url, use: :slugged
  
  mount_uploader :image, ImageUploader
  has_one :video
  
  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  validates :description, presence: true, length: { maximum: 100 }
  extend FriendlyId
  friendly_id :title_url, use: :slugged
  
	acts_as_votable
  mount_uploader :image, ImageUploader
	mount_uploader :thumbnail_image, ImageUploader
	mount_uploader :lesson_video, VideoUploader
  #belongs_to :tutorial
	has_one :video
  belongs_to :section
	#has_many :comments, dependent: :destroy

	

  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :lessons
  belongs_to :tutorial
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  ratyrate_rateable "rate"
  validates :description, presence: true, length: { maximum: 400 }
	mount_uploader :images, ImageUploader
  #has_many :lessons
  has_many :sections
  belongs_to :tutorial_type
  acts_as_commontable
  
  extend FriendlyId
  friendly_id :title_url, use: :slugged

  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/tutorial_type.rb
class TutorialType < ApplicationRecord
  
  extend FriendlyId
  friendly_id :title_url, use: :slugged

  has_many :tutorials
  belongs_to :category

  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ratyrate_rater
	acts_as_voter
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
	#has_many :comments, dependent: :destroy
	acts_as_commontator
end

app/models/video.rb
class Video < ApplicationRecord
	belongs_to :lesson
  belongs_to :course
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :index]

  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.all
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
    commontator_thread_show(@tutorial)
  end

  # GET /tutorials/new
  def new
    @tutorial = Tutorial.new
  end

  # GET /tutorials/1/edit
  def edit
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    @tutorial = Tutorial.new(tutorial_params)

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully created.' }
        format.json { render :show, status: :created, location: @tutorial }
      else
        format.html { render :new }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorials/1
  # PATCH/PUT /tutorials/1.json
  def update
    respond_to do |format|
      if @tutorial.update(tutorial_params)
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutorial }
      else
        format.html { render :edit }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    @tutorial.destroy
    respond_to do |format|
      format.html { redirect_to tutorials_url, notice: 'Tutorial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorial
      @tutorial = Tutorial.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutorial_params
      params.require(:tutorial).permit(:title, :description, :images, :title_url)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
	def display_likes(lesson)
		votes = lesson.votes_for.up.by_type(User)
		return list_likers(votes) if votes.size <= 3
		count_likers(votes)
	end
	
	def liked_lesson(lesson)
		if user_signed_in?
			return 'fa fa-heart' if current_user.voted_for? lesson
			'fa fa-heart-o'
		end
	end
	
	def last_models(number)
		if number <= Lesson.count
			Lesson.last(number)	
		end
	end
	
	private

	def all_lessons
		Lesson.last(3)
	end
	
	def list_likers(votes)
		emails = []
		unless votes.blank?
			votes.voters.each do |voter|
				emails.push(voter.email, class: 'some')
			end
			emails.to_sentence.html_safe + like_plural(votes)
	end
end

	def count_likers(votes)
		vote_count = votes.size
		vote_count.to_s + ' likes'
	end
	
	def like_plural(votes)
		return ' like this' if votes.count > 1
		' likes this'
	end
end
	

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/tutorials/_form.html.erb
<%= form_for(tutorial) do |f| %>
  <% if tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
      <% tutorial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <div class="filed">
  	<%= f.file_field :images %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tutorials/_tutorials_index.html.erb
<!-- <div id="masonry-container" class="transitions-enabled centered infinite-scroll clearfix"> -->
	<% tutorials.each do |tutorial| %>
	  <!-- <div class="box col4"> -->
    <div class="col-md-4 col-xs-4 col-sm-4 pull-right">
			<div class="well">
	      <%= image_tag tutorial.images.url, size: '100x100', class: 'img-responsive' if tutorial.images? %>
	      <h2><%= link_to tutorial.title, tutorial_path(tutorial) %></h2>
	      <p><%= markdown(tutorial.description) %></p>
				<div class="lesson-count">
					<span><i class="fa fa-leanpub" aria-hidden="true"></i> <%#= tutorial.count %> درس</span>
				</div>
	    </div>
		</div>
	<% end %>
<!-- </div> -->

app/views/tutorials/edit.html.erb
<h1>Editing Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Show', @tutorial %> |
<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<section id="tutorial-index">
	<div class="container">
		<div class="page-header">
			<h1>دسته ها</h1>
		</div>
		<div class="row">
			<%= render 'tutorials_index', tutorials: @tutorials %>
		</div>
	</div>
</section>

app/views/tutorials/new.html.erb
<h1>New Tutorial</h1>

<%= render 'form', tutorial: @tutorial %>

<%= link_to 'Back', tutorials_path %>

app/views/tutorials/show.html.erb
<% title @tutorial.title %>
<section id="lessons-index">
	
	<div class="ui grid container">
		<!-- <div class="row"> -->
			
			<div class="fourteen wide column row">
				<h1 class="ui header"><%= @tutorial.title %></h1>
				<h4 class="ui horizontal divider header"><i class="angle down icon"></i></h4>
			</div>
			
			<div class="fourteen wide column row">
				<%= @tutorial.description %>
			</div>
			
			<% if user_signed_in? %>
				<div class="eight wide column">
					<div class="ui relaxed list">
						<% @tutorial.sections.each do |section| %>
							<div class="item">
								<div class="ui styled accordion">
								  <div class="title">
								    <i class="dropdown icon"></i>
								    <%= section.title %>
								  </div>
								  <div class="content">
										<% section.lessons.each do |lesson| %>
								    	<%= link_to lesson.title, lesson %>
										<% end %>
								  </div>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			<% end %>
			
		<!-- </div> -->
	</div>
	<div class="ui grid container">
		<div class="sixteen wide column">
			<%= commontator_thread(@tutorial) %>
		</div>
	</div>
</section>

<!--*******************************************************-->

	