config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  #resources :categories, only: [:index]
  root 'welcome#index'
  resources :courses, only: [:show, :index]
	devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations" }
  devise_for :admins, path: 'admin', skip: [:registrations]
	mount RailsAdmin::Engine => '/user_admin', as: 'rails_admin'
	mount Commontator::Engine => '/commontator'
  
  resources :blogs, path: "blog", only: [:show, :index]
  
	# get '/courses', to: redirect("http://courses.shetabyad.com/")
  
	get 'about-us', to: :about_us, controller: 'welcome'
	match '/contacts', path: 'contact-us', to: 'contacts#new', via: 'get'
	resources 'contacts', path: 'contact-us', only: [:new, :create]
	
  resources :tutorials, only: [:show, :index]
	
  
	#authenticate :user do 
		resources :lessons, only: [:show, :index] do 
			member do
				get 'like'
			end
		end
	#end
  
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  
  resources :tutorial_types, path: "", only: [:show]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :blogs
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/blog.rb
class Blog < ApplicationRecord
  
  extend FriendlyId
  friendly_id :title_url, use: :slugged
  
  mount_uploader :picture, ImageUploader
  
  belongs_to :admin
  
  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tutorial_types
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true
  attribute :tel,       :validate => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "پیام کاربر از شتابیاد",
      :to => "info@shetabyad.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/course.rb
class Course < ApplicationRecord
  extend FriendlyId
  friendly_id :title_url, use: :slugged
  
  mount_uploader :image, ImageUploader
  has_one :video
  
  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  validates :description, presence: true, length: { maximum: 100 }
  extend FriendlyId
  friendly_id :title_url, use: :slugged
  
	acts_as_votable
  mount_uploader :image, ImageUploader
	mount_uploader :thumbnail_image, ImageUploader
	mount_uploader :lesson_video, VideoUploader
  #belongs_to :tutorial
	has_one :video
  belongs_to :section
	#has_many :comments, dependent: :destroy

	

  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :lessons
  belongs_to :tutorial
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
  ratyrate_rateable "rate"
  validates :description, presence: true, length: { maximum: 400 }
	mount_uploader :images, ImageUploader
  #has_many :lessons
  has_many :sections
  belongs_to :tutorial_type
  acts_as_commontable
  
  extend FriendlyId
  friendly_id :title_url, use: :slugged

  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/tutorial_type.rb
class TutorialType < ApplicationRecord
  
  extend FriendlyId
  friendly_id :title_url, use: :slugged

  has_many :tutorials
  belongs_to :category

  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ratyrate_rater
	acts_as_voter
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
	#has_many :comments, dependent: :destroy
	acts_as_commontator
end

app/models/video.rb
class Video < ApplicationRecord
	belongs_to :lesson
  belongs_to :course
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy, :like]
  skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    respond_to do |format|
      format.html
      format.js 
    end
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update_attributes(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
	
	def like
		if @lesson.liked_by current_user
			respond_to do |format|
				format.html { redirect_to :back }
				format.js
			end
		end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_lesson
      @lesson = Lesson.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:title, :description, :tutorial_id, :image, :thumbnail_image, :title_url, :lesson_video)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
	def display_likes(lesson)
		votes = lesson.votes_for.up.by_type(User)
		return list_likers(votes) if votes.size <= 3
		count_likers(votes)
	end
	
	def liked_lesson(lesson)
		if user_signed_in?
			return 'fa fa-heart' if current_user.voted_for? lesson
			'fa fa-heart-o'
		end
	end
	
	def last_models(number)
		if number <= Lesson.count
			Lesson.last(number)	
		end
	end
	
	private

	def all_lessons
		Lesson.last(3)
	end
	
	def list_likers(votes)
		emails = []
		unless votes.blank?
			votes.voters.each do |voter|
				emails.push(voter.email, class: 'some')
			end
			emails.to_sentence.html_safe + like_plural(votes)
	end
end

	def count_likers(votes)
		vote_count = votes.size
		vote_count.to_s + ' likes'
	end
	
	def like_plural(votes)
		return ' like this' if votes.count > 1
		' likes this'
	end
end
	

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/lessons/_form.html.erb
<%= form_for(lesson) do |f| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
	<div class="field">
		<%= f.file_field :image, accept: 'image/jpg,image/png' %>
	</div>
	<div class="field">
		<%= f.file_field :thumbnail_image, accept: 'image/jpg,image/png' %>
	</div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
  	<%= f.text_field :aparat_id %>
  	<%= f.text_field :aparat_embed %>
  	<%= f.text_field :youtube_embed %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/_lessons_index.html.erb
<section id="lessons-index">
	<div class="lessons-index-hero">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-xs-10 col-sm-10">
					<h1 class="text-center">همه آموزش ها</h1>
				</div>
				<div class="col-md-6">
					<% sum_like = 0 %>
					<% lessons.each do |lesson| %>
						<% sum_like += lesson.get_upvotes.size %>
					<% end %>
					<p><i class="fa fa-heart fa-lg"></i> [<%= sum_like %>] بار پسندیده شده</p>
					<p><i class="fa fa-play fa-lg"></i> [<%= Video.count %>] ویدئو</p>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row pull-right">
			<% lessons.each do |lesson| %>
				<div class="col-md-4 col-xs-8 col-sm-8">
					<div class="panel panel-default">
						<div class="panel-heading">
							<% if lesson.thumbnail_image? %>
								<%= image_tag lesson.thumbnail_image.url(:thumbnail), class: "img-responsive" %>
								<% unless lesson.video.nil? %>
									<i class="fa fa-play fa-2x pull-right play"></i>
								<% end %>
							<% end %>
							<h4><%= link_to lesson.title, lesson %></h4>
						</div>
						<div class="panel-body">
							<%= markdown(sanitize(lesson.description[0, 200] + '...')) %>
						</div>
						<div class="panel-footer">
							<i class="fa fa-heart fa-lg fa-like"></i><span class="like-number"><%= lesson.get_upvotes.size %></span>
							<i class="fa fa-comments fa-lg fa-comment"></i><span class="comment-number"><%= lesson.thread.comments.count %></span>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>		
</section>

app/views/lessons/_likes.html.erb
<div class="likes" id="likes_<%= lesson.id %>">
	<%= display_likes lesson %>
</div>

app/views/lessons/_list_lessons.html.erb
<div class="panel panel-default panel-list">
  <div class="panel-heading">آخرین آموزش ها</div>
    <% lessons.each do |lesson| %>
      <div class="panel-body list-lesson-body">
				<div class="thumbnail">
					<%= image_tag lesson.thumbnail_image, class: "img-responsive" if lesson.thumbnail_image? %>
	        <p><%= link_to lesson.title, lesson %></p>
				</div>
      </div>
  <% end %>
</div>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<%= render 'lessons_index', lessons: @lessons %>

app/views/lessons/like.js.erb
/* GLOBAl $ */
$("#like_<%= @lesson.id %>").removeClass('fa fa-heart-o').addClass('fa fa-heart');
$("#likes_<%= @lesson.id %>").html("<%= j (render partial: 'lessons/likes', locals: { lesson: @lesson }) %>");

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<section id="lesson-show">
	<div class="ui grid">
		<div class="fourteen wide column">
			<h1 class="ui header"><%= @lesson.title %></h1>
		</div>
		<div class="sixteen wide column">
			<video class="afterglow" id="myvideo" width="800" height="400">
	      <source type="video/mp4" src="<%= @lesson.lesson_video %>" />
	    </video>
		</div>
		<div class="fourteen wide column">
			<%= @lesson.description %>
		</div>
	</div>
</section>

<script>
	$(function () {
		$('[data-toggle="tooltip"]').tooltip()
	})
</script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-593a8f56bb059f35"></script> 
	
	
	
	

app/views/lessons/show.js.erb
//$('.ui.modal').html("<video class='afterglow' id='myvideo' width='800' height='400'><source type='video/mp4' src='<%= j @lesson.lesson_video %>' /></video> ");

$('.ui.modal').html(" j <%= @lesson.title %>");